name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          github-token: ${{ secrets.BUILD_TOKEN }}
          push: true
          tags: |
            xhudaman/node-pnpm:lts-alpine
            xhudaman/node-pnpm:latest
